[:author-email ""
 :author-name ""
 :blog-as-index nil
 :default-template "default.clj"
 :create-archives false
 :create-rss false
 :encoding "UTF-8"
 :in-dir "site-src/"
 :out-dir "html/"
 :posts-per-page 1
 :site-keywords ""
 :site-description ""
 :site-url "https://rk222ev.github.io/dungeons/"
 :url-base ""
 :site-title "dungeons"]
